package lawisAddonDqr2.config;

import cpw.mods.fml.common.ModMetadata;
import lawisAddonDqr2.LawisAddonDQR02;

/*
 * mcmod.infoと同様の内容。
 * modの情報を登録するためのクラス。
 *
 * preInitで最初に呼び出す。
 */
public class Lad2InfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = LawisAddonDQR02.MOD_ID;
		meta.name = LawisAddonDQR02.MOD_NAME;
		meta.description = "Lawi's Addon for DQR #02";
		meta.version = LawisAddonDQR02.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
